"""
Generate the dataset manifest: file listing with example counts, author
attribution, and SHA-256 checksums. Used in the dataset card for credit
protection and reproducibility.

Re-run before training; commit the output to git so the manifest is
version-controlled alongside the data it describes.

Usage:
    python manifest.py             # print to stdout
    python manifest.py > MANIFEST.md
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


def main() -> None:
    script_dir = Path(__file__).parent
    rows: list[tuple[str, int, str, str]] = []
    total_examples = 0

    for path in sorted(script_dir.rglob("*.jsonl")):
        # Skip audit-tests/ — those are synthetic-bad examples for QA, not training data.
        if "audit-tests" in path.parts:
            continue
        examples = 0
        authors: set[str] = set()
        with path.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                examples += 1
                author = row.get("metadata", {}).get("author", "")
                if author:
                    authors.add(author)
        total_examples += examples
        sha = hashlib.sha256(path.read_bytes()).hexdigest()[:12]
        rel = path.relative_to(script_dir).as_posix()
        auth = ",".join(sorted(authors)) if authors else "unattributed"
        rows.append((rel, examples, auth, sha))

    print(f"# Three Babies Curriculum Manifest\n")
    print(f"Total examples: **{total_examples}**\n")
    print(f"Files: **{len(rows)}**\n")
    print("| File | Examples | Author(s) | SHA-256 (12) |")
    print("|------|----------|-----------|--------------|")
    for rel, n, auth, sha in rows:
        print(f"| `{rel}` | {n} | {auth} | `{sha}` |")
    print()
    print("Generated by `manifest.py`. Re-run before training.")


if __name__ == "__main__":
    main()
